targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "lib/{{dir}}/{{file}}.dart": "lib/{{dir}}/build/{{file}}.g.dart"
      freezed:
        options:
          build_extensions:
            "lib/{{dir}}/{{file}}.dart": "lib/{{dir}}/build/{{file}}.freezed.dart"
