name: solo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.21.2
  freezed: ^3.1.0
  collection: ^1.19.0
  go_router: ^16.0.0
  flutter_native_splash: ^2.4.4
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.3
  source_gen: ^2.0.0
  riverpod_annotation: ^2.6.1
  dotted_border: ^3.1.0
  hooks_riverpod: ^2.6.1
  table_calendar: ^3.1.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  flutter_launcher_icons: ^0.14.4
  audioplayers: ^6.5.0
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
          weight: 400

flutter_icons:
  ios: true
  image_path: "assets/icon/launcher/icon_ios.png"
  remove_alpha_ios: true
  android: true
  adaptive_icon_background: "assets/icon/launcher/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/icon/launcher/icon_adaptive_foreground.png"
