name: solo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  freezed: ^2.5.8
  collection: ^1.19.0
  go_router: ^14.7.2
  flutter_native_splash: ^2.4.4
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.3
  source_gen: ^2.0.0
  riverpod_annotation: ^2.6.1
  dotted_border: ^2.1.0
  hooks_riverpod: ^2.6.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.24.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
