name: 🐛 バグ報告 (Claude Code対応)
description: Claude Codeでの効率的なバグ修正のための詳細なバグ報告
title: "[バグ]: "
labels: ["bug", "claude-code"]
body:
  - type: markdown
    attributes:
      value: |
        ## Claude Code バグ報告テンプレート
        
        このテンプレートはClaude Codeでの効率的なデバッグに最適化されています。
        Claude Codeが問題を素早く理解・修正できるよう、できるだけ多くの情報を提供してください。

  - type: textarea
    id: bug-description
    attributes:
      label: バグの説明
      description: バグの内容を明確かつ簡潔に説明してください
      placeholder: "タイマーボタンが表示されない..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 再現手順
      description: 問題を再現するための詳細な手順
      placeholder: |
        1. ○○画面に移動
        2. ○○ボタンをタップ
        3. ○○を入力
        4. ○○が発生することを確認
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 本来どのような動作をするべきか
      placeholder: "タイマーボタンが表示され、タップできるはず..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 実際に何が起こっているか
      placeholder: "タイマーボタンが表示されない/動作しない..."
    validations:
      required: true

  - type: textarea
    id: affected-files
    attributes:
      label: 関連ファイル/コンポーネント
      description: このバグに関連する具体的なファイル、クラス、コンポーネントをリストアップ
      placeholder: |
        - lib/screen/widgets/timer/timer_main.dart
        - lib/services/todo_service.dart
        - lib/models/todo_model.dart
      value: |
        - 
        - 
        - 

  - type: textarea
    id: error-logs
    attributes:
      label: エラーメッセージ/ログ
      description: エラーメッセージ、コンソール出力、関連するログを含めてください
      placeholder: |
        ```
        flutter: Error: ...
        flutter: Stack trace: ...
        ```
      render: shell

  - type: textarea
    id: code-context
    attributes:
      label: 関連するコードコンテキスト
      description: 問題に関連する可能性のあるコードスニペットを含めてください
      placeholder: |
        ```dart
        // timer_main.dart の123行目付近
        if (timerSession.mode == TimerMode.pomodoro) {
          // ここに問題がある可能性
        }
        ```
      render: dart

  - type: dropdown
    id: severity
    attributes:
      label: 重要度
      description: このバグはどの程度深刻ですか？
      options:
        - 致命的 (アプリがクラッシュ/使用不可)
        - 高 (主要機能が破損)
        - 中 (機能が部分的に破損)
        - 低 (軽微な問題/見た目の問題)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: 発生頻度
      description: どのくらいの頻度で発生しますか？
      options:
        - 常に (100%)
        - 頻繁に (>75%)
        - 時々 (25-75%)
        - 稀に (<25%)
        - 一度だけ
    validations:
      required: true

  - type: textarea
    id: device-info
    attributes:
      label: デバイス/環境情報
      description: プラットフォームとバージョン情報
      placeholder: |
        - OS: macOS 13.0, iOS 16.0, Android 12 など
        - Flutter version: 3.16.0
        - Device: iPhone 14, Pixel 7 など
        - App version: 1.0.0
      value: |
        - OS: 
        - Flutter version: 
        - Device: 
        - App version: 

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: その他の関連情報、スクリーンショット、参考情報があれば記載してください
      placeholder: |
        - スクリーンショット/動画
        - 関連するissue
        - 試したワークアラウンド
        - 関連する可能性のある最近の変更

  - type: checkboxes
    id: claude-code-checklist
    attributes:
      label: Claude Code サポートチェックリスト
      description: Claude Codeがより良いサポートを提供するためのチェックリスト
      options:
        - label: CLAUDE.mdの関連するコーディングガイドラインを確認しました
        - label: 問題が発生している可能性のある具体的なファイルパスを提供しました
        - label: 関連するエラーメッセージやログを含めました
        - label: 修正のテストやフィードバックを提供できます
        - label: 必要に応じて追加の情報を提供できます