name: ❓ Question/Help (Claude Code Optimized)
description: Ask questions about code architecture, implementation, or best practices
title: "[Question]: "
labels: ["question", "claude-code", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ## Claude Code Question Template
        
        This template helps you get better answers from Claude Code by providing sufficient context
        about your codebase and specific questions.

  - type: textarea
    id: question
    attributes:
      label: Main Question
      description: What specific question do you have?
      placeholder: "How should I implement real-time collaboration for the todo list feature?"
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What category does your question fall into?
      options:
        - Architecture/Design
        - Implementation Approach
        - Best Practices
        - Code Review/Feedback
        - Performance Optimization
        - Testing Strategy
        - Debugging Help
        - Tool/Library Recommendation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Background
      description: Provide context about your situation
      placeholder: |
        - What are you trying to achieve?
        - What's the broader context of this question?
        - What constraints do you have?
        - What research have you already done?
    validations:
      required: true

  - type: textarea
    id: current-approach
    attributes:
      label: Current Approach/Code
      description: Show what you've tried or what you're considering
      placeholder: |
        ```dart
        // Current implementation or approach you're considering
        class TodoService {
          // Relevant code here...
        }
        ```
      render: dart

  - type: textarea
    id: relevant-files
    attributes:
      label: Relevant Files/Components
      description: List files or components related to your question
      placeholder: |
        - lib/services/todo_service.dart
        - lib/models/todo_model.dart
        - lib/screen/states/todo_state.dart
      value: |
        - 
        - 
        - 

  - type: textarea
    id: specific-challenges
    attributes:
      label: Specific Challenges/Concerns
      description: What specific problems or concerns do you have?
      placeholder: |
        - How to handle concurrent updates?
        - Performance impact of real-time sync
        - State management complexity
        - Database schema considerations

  - type: textarea
    id: requirements
    attributes:
      label: Requirements & Constraints
      description: What requirements or constraints should the solution meet?
      placeholder: |
        - Must work offline
        - Should follow CLAUDE.md guidelines
        - Performance is critical
        - Must integrate with existing authentication
        - Budget/time constraints

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: |
        - WebSocket-based real-time updates
        - Polling-based approach
        - Using Firebase Firestore
        - Custom WebRTC implementation

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is getting an answer to this question?
      options:
        - Critical (Blocking development)
        - High (Needed soon for planning)
        - Medium (Helpful for current work)
        - Low (General knowledge/future planning)

  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What kind of answer or help are you looking for?
      placeholder: |
        - Detailed implementation guidance
        - Architectural recommendations
        - Code examples
        - Best practice suggestions
        - Tool/library recommendations
        - Code review and feedback

  - type: checkboxes
    id: claude-code-checklist
    attributes:
      label: Claude Code Assistance Checklist
      description: Help Claude provide better answers
      options:
        - label: I have checked CLAUDE.md for relevant guidelines
        - label: I have searched existing issues for similar questions
        - label: I have provided sufficient context about my codebase
        - label: I have clearly stated my specific question
        - label: I am open to different approaches and suggestions
        - label: I can provide additional context if needed