name: ❓ 質問/ヘルプ (Claude Code対応)
description: コードアーキテクチャ、実装、ベストプラクティスについての質問
title: "[質問]: "
labels: ["question", "claude-code", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ## Claude Code 質問テンプレート
        
        このテンプレートは、コードベースに関する十分な情報を提供することで、
        Claude Codeからより良い回答を得るのに役立ちます。

  - type: textarea
    id: question
    attributes:
      label: 主な質問
      description: どのような具体的な質問がありますか？
      placeholder: "Todoリスト機能にリアルタイムコラボレーションを実装するにはどうすべきでしょうか？"
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: 質問の種類
      description: あなたの質問はどのカテゴリに該当しますか？
      options:
        - アーキテクチャ/設計
        - 実装アプローチ
        - ベストプラクティス
        - コードレビュー/フィードバック
        - パフォーマンス最適化
        - テスト戦略
        - デバッグヘルプ
        - ツール/ライブラリ推奨
        - その他
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 背景と状況
      description: あなたの状況について背景を提供してください
      placeholder: |
        - 何を達成しようとしていますか？
        - この質問のより広い背景は何ですか？
        - どのような制約がありますか？
        - すでにどのような調査をしましたか？
    validations:
      required: true

  - type: textarea
    id: current-approach
    attributes:
      label: 現在のアプローチ/コード
      description: 試したことや検討していることを示してください
      placeholder: |
        ```dart
        // 現在の実装または検討しているアプローチ
        class TodoService {
          // 関連するコードをここに...
        }
        ```
      render: dart

  - type: textarea
    id: relevant-files
    attributes:
      label: 関連ファイル/コンポーネント
      description: あなたの質問に関連するファイルやコンポーネントをリストアップ
      placeholder: |
        - lib/services/todo_service.dart
        - lib/models/todo_model.dart
        - lib/screen/states/todo_state.dart
      value: |
        - 
        - 
        - 

  - type: textarea
    id: specific-challenges
    attributes:
      label: 具体的な課題/懸念事項
      description: どのような具体的な問題や懸念がありますか？
      placeholder: |
        - 同時更新をどう処理するか？
        - リアルタイム同期のパフォーマンス影響
        - 状態管理の複雑さ
        - データベーススキーマの考慮事項

  - type: textarea
    id: requirements
    attributes:
      label: 要件と制約
      description: ソリューションが満たすべき要件や制約は何ですか？
      placeholder: |
        - オフラインで動作する必要がある
        - CLAUDE.mdガイドラインに従うべき
        - パフォーマンスが重要
        - 既存の認証と統合する必要がある
        - 予算/時間の制約

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 検討した代替案
      description: どのような他のアプローチを検討しましたか？
      placeholder: |
        - WebSocketベースのリアルタイム更新
        - ポーリングベースのアプローチ
        - Firebase Firestoreの使用
        - カスタムWebRTC実装

  - type: dropdown
    id: urgency
    attributes:
      label: 緊急度
      description: この質問への回答はどの程度緊急ですか？
      options:
        - 致命的 (開発をブロック)
        - 高 (計画のために近いうちに必要)
        - 中 (現在の作業に役立つ)
        - 低 (一般的な知識/将来の計画)

  - type: textarea
    id: expected-outcome
    attributes:
      label: 期待する回答
      description: どのような種類の回答やヘルプを求めていますか？
      placeholder: |
        - 詳細な実装ガイダンス
        - アーキテクチャの推奨事項
        - コード例
        - ベストプラクティスの提案
        - ツール/ライブラリの推奨
        - コードレビューとフィードバック

  - type: checkboxes
    id: claude-code-checklist
    attributes:
      label: Claude Code サポートチェックリスト
      description: Claude Codeがより良い回答を提供するためのチェックリスト
      options:
        - label: CLAUDE.mdの関連するガイドラインを確認しました
        - label: 類似の質問について既存のissueを検索しました
        - label: コードベースについて十分な情報を提供しました
        - label: 具体的な質問を明確に述べました
        - label: 異なるアプローチや提案に対してオープンです
        - label: 必要に応じて追加の情報を提供できます