name: パフォーマンス問題 / Performance Issue
description: アプリの速度や応答性の問題報告（GitHub Copilot最適化）
title: "[PERFORMANCE] "
labels: ["performance", "copilot-friendly"]
body:
  - type: markdown
    attributes:
      value: |
        ## パフォーマンス問題 / Performance Issue
        このテンプレートは GitHub Copilot agent がパフォーマンス改善コードを生成しやすいように設計されています。

  - type: input
    id: performance-title
    attributes:
      label: 問題の概要 / Performance Issue Summary
      description: 問題の要点を簡潔に記述
      placeholder: "例: 勤怠記録画面の表示が非常に遅い"
    validations:
      required: true

  - type: checkboxes
    id: operations
    attributes:
      label: 発生操作 / Operations Where Issue Occurs
      description: 該当するもの全てにチェック
      options:
        - label: アプリ起動時 / App startup
        - label: ページ遷移 / Page navigation
        - label: データ読み込み / Data loading
        - label: 勤怠データ保存 / Work time data saving
        - label: UI操作 / UI operation
        - label: その他 / Other

  - type: checkboxes
    id: symptoms
    attributes:
      label: 症状 / Specific Symptoms
      description: 該当するもの全てにチェック
      options:
        - label: 動作が遅い / Slow operation
        - label: フリーズする / Freezing
        - label: 応答しない / Unresponsive
        - label: メモリ消費が多い / High memory usage
        - label: バッテリー消費が激しい / High battery consumption
        - label: 発熱 / Device heating
        - label: その他 / Other

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順 / Steps to Reproduce
      description: 問題を再現するための具体的な手順
      placeholder: |
        1. 勤怠記録画面を開く
        2. データを表示する
        3. 表示が遅いことを確認
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: 期待するパフォーマンス / Expected Performance
      description: 期待する動作や速度
      placeholder: |
        例: 画面表示が2秒以内に完了する
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: 実際のパフォーマンス / Actual Performance
      description: 現在発生している問題の詳細
      placeholder: |
        例: 画面表示に10秒以上かかる
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 環境情報 / Environment
      description: デバイス・OS・アプリバージョン等
      placeholder: |
        例:
        - デバイス: iPhone 12, Pixel 5
        - OS: iOS 17, Android 14
        - アプリバージョン: v1.2.3
        - メモリ容量: 4GB RAM
        - ストレージ空き容量: 32GB available
    validations:
      required: true

  - type: textarea
    id: data-scale
    attributes:
      label: データ規模 / Data Scale
      description: 登録ユーザー数やデータ件数など
      placeholder: |
        例:
        - 登録ユーザー数: 10人
        - 勤怠記録数: 100件/月

  - type: textarea
    id: performance-measurements
    attributes:
      label: パフォーマンス測定値 / Performance Measurements
      description: 具体的な測定値があれば記載
      placeholder: |
        例:
        - 読み込み時間: 10秒
        - メモリ使用量: 200MB

  - type: textarea
    id: additional-info
    attributes:
      label: 補足情報 / Additional Info
      description: 追加情報やログがあれば記載
      placeholder: "例: スクリーンショットや参考URL"
